# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ace3468a86b328b1316996f2ed1b01d7"
name = "order-pdf-generator"
application_url = "https://english-fa-personality-thick.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "nobu-checkout-extensibility2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://english-fa-personality-thick.trycloudflare.com/auth/callback",
  "https://english-fa-personality-thick.trycloudflare.com/auth/shopify/callback",
  "https://english-fa-personality-thick.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
